version: '3'

networks:
    internal:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
          - "80:80"
        volumes:
          - ./dev:/var/www
          - ./config/nginx:/etc/nginx/conf.d
          - ./data/logs:/var/log/nginx/
        depends_on:
          - php
          - postgres
          - mysql
        networks:
          - internal
    php:
        image: php:8.3
        build:
          context: ./config/php
          dockerfile: Dockerfile
        container_name: php
        volumes:
          - ./dev:/var/www
          - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
          - "9000:9000"
        networks:
          - internal
    mysql:
        image: mysql:latest
        container_name: mysq
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        # command: --innodb_use_native_aio=0
        ports:
          - 3306:3306
        volumes:
          - ./database/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 7212104
        networks:
         - internal      
    postgres:
        image: postgres:latest
        container_name: postgres
        command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
        ports:
         - 5432:5432
        volumes:
         - ./database/postgres:/data/postgres
        networks:
         - internal 
        environment:
         POSTGRES_HOST: localhost   
         POSTGRES_HOST_AUTH_METHOD: trust
         POSTGRES_PASSWORD: 7212104
         POSTGRES_USER: postgres
         PGDATA : /data/postgres
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: alexandershtyher@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 7212104
        links:
            - postgres
        ports:
            - 5050:80
        volumes:
            - ./database/pgadmin:/var/lib/pgadmin       
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        links:
          - mysql
        ports:
           - 8082:80
        environment:
           - PMA_ARBITRARY=1
        networks:
         - internal        
